<?php $this->placeholder("title")->set($this->_( "Billing edition") )?>
<h2><?php echo $this->billing["date"] ?> <?php if( $this->billing["billing_status"] == 0):?>
<a class="button orange_btn" href="javascript:publishBilling()"><span><span><?php echo $this->_("publish the bill")?></span></span></a>
<?php endif;?></h2>

<h3><?php echo $this->_("Overview")?></h3>

<span>


<p>
<ul>
<?php $currency = "Eur";?>
	<li><?php echo $this->_("Client")?> : <?php echo $this->organization[0]["name"]?></li>
	<li><?php echo $this->_("Production")?> : <?php echo $this->production[0]["name"]?></li>
	<li><?php echo $this->_("Currency")?> : <?php echo $currency ?></li>
</ul>
</p>

<fieldset class="panel"><legend><?php echo $this->_("CDN (Content Delivery Network) consumption")?></legend>

<div>
<table id="data" class="tablesorter display table">
	<thead>
		<tr>
			<th width="70%"><?php echo $this->_ ( "Type" );?></th>
			<th><?php echo $this->_ ( "Amount (Giga Bytes)" );?></th>
			<th><?php echo $this->_ ( "Unitary price (Giga Bytes)" );?></th>
			<th><?php echo $currency ?></th>

		</tr>
	</thead>
	<tbody>

	<?php $total = 0;?>

		<tr class="odd">
			<td><?php echo $this->_("Storage")?></td>
			<td><?php 
			$bs = new Zend_Measure_Binary( $this->billing["bytes_stored"],Zend_Measure_Binary::BYTE);
			$bs->convertTo(Zend_Measure_Binary::GIGABYTE) ;
			echo $bs->toString(4) ?></td>
			<td><?php echo $this->billing["gb_stored"] ?></td>
			<td><?php $tmp =  round($this->billing["bytes_stored_cost"],2);
			echo $tmp ;$total += $tmp?></td>

		</tr>


		<tr class="even">

			<td><?php echo $this->_("Streaming")?></td>
			<td><?php 
			$bst = new Zend_Measure_Binary( $this->billing["bytes_streamed_logs"],Zend_Measure_Binary::BYTE);
			$bst->convertTo(Zend_Measure_Binary::GIGABYTE) ;
			echo $bst->toString(4)
			?> <br />
			<?php //echo $this->billing["bytes_streamed_logs"] ?></td>
			<td><?php echo $this->billing["gb_streamed"] ?></td>
			<td><?php $tmp = round($this->billing["bytes_streamed_cost"],2);echo $tmp ;$total += $tmp ?></td>
		</tr>
	</tbody>
</table>
</div>
</fieldset>

<fieldset class="panel"><legend><?php echo $this->_("Complete billing")?>
</legend>
<div><?php if( $this->billing["billing_status"] == 0):?> 
	<?php echo $this->sexybutton ("href", $this->_("Add a billing line"), array("add_new"), "javascript:void(0)"   ,array("id"=>"btnBillingLine")) ?>
			<?php endif;?>
<table id="data" class="tablesorter display table">
	<thead>
		<tr>
			<th width="70%"><?php echo $this->_("wording")?></th>
			<th><?php echo $currency ?></th>
			<th></th>
		</tr>
	</thead>
	<tbody>
	<?php foreach ($this->billlines["+"] as $item): ?>
		<tr class="<?php echo $this->cycle(array("odd","even"))->next()?>">
			<td><?php echo $item["libelle"]?></td>
			<td><?php echo $item["amount"];$total += $item["amount"]?></td>
			<td><?php if( $this->billing["billing_status"] == 0):?>
			<div class="actions_menu">
			<ul>
				<li><a class="delete"
					href="<?php echo $this->url(array( "action" => "deleteline","controller"=>"billings","module"=>$this->getParam("module"),"idbilling"=>$item["idbilling"],"idline"=>$item["idbillingother"]),null,true) ?>"><?php echo $this->_("delete") ?></a></li>
			</ul>
			</div>
			<?php endif;?></td>
		</tr>
		<?php endforeach; ?>
	</tbody>
</table>

<div id="formBillingLine">

<h3><?php echo $this->_("Add a billing line")?></h3>
<form method="post"
	action="<?php echo $this->url(array("controller"=>"billings","module"=>"sadmin","action"=>"addbillingline"),null,true)?>">
<fieldset class="small">

<p><label><?php echo $this->_("wording")?></label> <span><?php echo $this->formText("libelle")?></span>
</p>
<p><label><?php echo $this->_("Amount")?></label> <span><?php echo $this->formText("amount")?></span>
</p>
		<?php echo $this->formHidden("idbilling",$this->getParam("idbilling"))?>
		<?php echo $this->formHidden("type","+")?>
<p><label>&nbsp;</label> <span><?php echo $this->sexybutton ("submit", $this->_("save"), array("send_form_btn"), null) ?></span></p>
</fieldset>
</form>

</div>



</div>
</fieldset>


<fieldset class="panel"><legend><?php echo $this->_("Discount  billing")?></legend>
<div><?php if( $this->billing["billing_status"] == 0):?>
<?php echo $this->sexybutton ("href", $this->_("Add a discount line"), array("add_new"), "javascript:void(0)"   ,array("id"=>"btnDiscountLine")) ?>

		<?php endif;?>
<table id="data" class="tablesorter display table">
	<thead>
		<tr>
			<th width="70%"><?php echo $this->_ ( "libelle" );?></th>
			<th><?php echo $currency ?></th>
			<th></th>
		</tr>
	</thead>
	<tbody>
	<?php foreach ($this->billlines["-"] as $item): ?>
		<tr class="<?php echo $this->cycle(array("odd","even"))->next()?>">
			<td><?php echo $item["libelle"]?></td>
			<td><?php echo $item["amount"];$total -= $item["amount"]?></td>
			<td><?php if( $this->billing["billing_status"] == 0):?>
			<div class="actions_menu">
			<ul>
				<li><a class="delete"
					href="<?php echo $this->url(array( "action" => "deleteline","controller"=>"billings","module"=>$this->getParam("module"),"idbilling"=>$item["idbilling"],"idline"=>$item["idbillingother"]),null,true) ?>"><?php echo $this->_("delete") ?></a></li>
			</ul>
			</div>
			<?php endif;?></td>
		</tr>
		<?php endforeach; ?>
	</tbody>
</table>

<div id="formDiscountLine">

<h3><?php echo $this->_("Add a discount line")?></h3>
<form method="post"
	action="<?php echo $this->url(array("controller"=>"billings","module"=>"sadmin","action"=>"addbillingline"),null,true)?>">
<fieldset class="small">

<p><label><?php echo $this->_("wording")?></label> <span><?php echo $this->formText("libelle")?></span>
</p>
<p><label><?php echo $this->_("Amount")?></label> <span><?php echo $this->formText("amount")?></span>
</p>
		<?php echo $this->formHidden("idbilling",$this->getParam("idbilling"))?>
		<?php echo $this->formHidden("type","-")?>
<p><label>&nbsp;</label> <span><?php echo $this->sexybutton ("submit", $this->_("save"), array("send_form_btn"), null) ?></span></p>
</fieldset>
</form>

</div>


</div>
</fieldset>


<fieldset class="panel"><legend><?php echo $this->_("Total resume")?></legend>
<div><?php if( $this->billing["billing_status"] == 0):?> <?php if($this->billing["rate_discount"] == "" || $this->billing["rate_discount"] == 0):?>
<?php echo $this->sexybutton ("href", $this->_("Add  discount rate"), array("add_new"), "javascript:addDiscountRate()"   ,array("id"=>"btnDiscountLine")) ?>
<?php echo $this->sexybutton ("href",  $this->_("Remove discount rate") , array("red_btn","delete"),   $this->url(array("action"=>"setrate","rate"=>0))   ,array("id"=>"")) ?>

	<?php endif;?> <?php endif;?>

<table id="data" class="tablesorter display table">
	<thead>
		<tr>
			<th width="70%"><?php echo $this->_ ( "Type" );?></th>
			<th><?php echo $currency ?></th>
			<th></th>
		</tr>
	</thead>
	<tbody>

		<tr class="odd">
			<td><?php echo $this->_("Total billing")?></td>
			<td><?php echo $total ?></td>
			<td></td>
		</tr>

		<?php if($this->billing["rate_discount"] > 0):?>
		<tr class="even">
			<td><?php echo $this->_("Discount rate %")?></td>
			<td><?php echo $this->billing["rate_discount"] ; $total -= $total * ($this->billing["rate_discount"] / 100)?></td>
			<td></td>
		</tr>
		<?php endif; ?>
		<tr class="odd">
			<td><?php echo $this->_("Vat %")?></td>
			<td><?php echo $this->billing["vatrate"]?></td>
			<td></td>
		</tr>

		<tr class="resume">
			<td><?php echo $this->_("Total billing + vat")?></td>
			<td><span id="totBilling"><?php  echo $finalTotal = ZN_Math::ceiling($total+ ($total*($this->billing["vatrate"]/100)),2) ?></span></td>
			<td></td>
		</tr>
	</tbody>
</table>
</div>
</fieldset>



<script type="text/javascript">

function addDiscountRate(){
	if( rate = prompt("<?php echo $this->_("Indicate the disount rate to apply to this billing","none") ?>") ){
		document.location.href = "<?php echo $this->url(array("action"=>"setrate"))?>" + "/rate/"+rate;
	}
}
function publishBilling(){
	document.location.href = "<?php echo $this->url(array("action"=>"publish","tot"=>$finalTotal))?>";
	
}
	jQuery(document).ready(function(){

			$("#formDiscountLine, #formBillingLine").css("display","none");
			$("#btnDiscountLine").toggle(function(){
				$("#formDiscountLine").css("display","block");
			},function(){
				$("#formDiscountLine").css("display","none");
			});
			$("#btnBillingLine").toggle(function(){
				$("#formBillingLine").css("display","block");
			},function(){
				$("#formBillingLine").css("display","none");
			});
	});

</script>