<h3><?php echo $this->_("Total views for last 30 days") ?></h3>

	<br />
	<br /></p>
	
<?php echo $this->javascriptfile(BASE_URL."embeded/js/FusionCharts.js") ?>
<div id="chartdiv"></div>




<?php
$date = explode(",", $this->getParam("period", date("Y-m-d", time() - 3600 * 24) . "," . date("Y-m-d", time() - 3600 * 24)));
$date = "[\"" . implode("\",\"", $date) . "\"]";
?>


<script type="text/javascript">
jQuery(document).ready(function(){	
        var myChart = new FusionCharts(BASE_URL + "embeded/flash/Charts/Line.swf", "myChartId", "750", "450");
        myChart.setDataURL("<?php echo $this->dataUrl ?>");
        myChart.setTransparent(true);
        myChart.render("chartdiv");        
    			 
});        
</script>


