<?php if(hasService($this->id_type, 2)) : ?>
	<!-- Encoding -->
	<script type="text/javascript">
		chb.push("encoding");
	</script>
	
	<div class="blocInfos" id="encoding_blocInfos" style="<?php if($this->getParam("action") != "view" && $this->getParam("action") != "processing") :?> display:none<?php endif; ?>">
		<h2>
			<?php echo $this->_("Encoding") ?>
		</h2>	
		<span class="rubInfos">
			<?php if($this->index == 1) : ?>
				<?php echo $this->_("Edit service encoding")?>
			<?php else: ?>
				<?php echo $this->_("View service encoding"); ?>
			<?php endif; ?>	
		</span>	
		<div class="moreinfos">
		
			<fieldset>	
			<?php if ((strlen($this->encoding[0]["comments"])) || ($this->index == 1)) :?>
			<p>		
				<label>				
					<?php echo $this->_ ( "Comments (formats)" )?>
				</label> 
				<?php if($this->index == 1) : ?>		
					<textarea
						name="encoding_comments" 
						id="encoding_comments" 
						rows="15" 
						cols="80"><?php echo $this->formats ?></textarea>	
				<?php else: ?>
					<span class="TEXTAREA_value">
						<?php echo nl2br($this->encoding[0]["comments"]) ?>
					</span>
				<?php endif; ?>
			</p>
			<?php endif; ?>
	
			<?php if($this->index != 1) : ?>
				<p>
					<label>
						<?php echo $this->_ ( "Current status"  )?>
					</label> 
					<span class="TEXT_value">
						<?php echo $this->_ ($this->encoding[0]["status"]) ?>
					</span>				
				</p>
			<?php endif; ?>
			
			<?php if($this->index == 2
			&& !isEnded($this->order[0]["status"])
			&& !isEnded($this->encoding[0]["status"])
			) : ?>
				<p>
					<label>
						<?php echo $this->_ ( "Status" )?>
					</label> 
					<span class="TEXT_value">
						<?php
							$service_states = serviceStateSelection($this->order[0]["status"], $this->encoding[0]["status"]);								
						?>
						<select id="encoding_list_state" name="encoding_list_state">
						<?php 							 
							foreach ($service_states as $state)
							{
								echo "<option>" . $this->_ ($state) . "</option>\n";
							}	
						?>		
						</select>		
					</span>				
				</p>
			<?php endif; ?>
	
			</fieldset>
		
	    </div>
	</div>
<?php endif;?>