<!-- CSS -->

<?php echo $this->cssfile( BASE_URL."themes/default/css/ColorPicker.css") ?>
<?php echo $this->cssfile( BASE_URL."themes/system/css/tablesorter_blue.css") ?>
<?php echo $this->cssfile( BASE_URL."themes/system/css/tree/apple/style.css") ?>

<?php echo $this->cssfile( BASE_URL."themes/system/css/validationEngine.jquery.css") ?>
<link rel="stylesheet" type="text/css" href="<?php echo BASE_URL?>themes/system/services/services.css"  
/>

<!-- SCRIPTS -->

<script 
	type="text/javascript"
	src="<?php echo BASE_URL?>embeded/js/jquery.meio.mask.js">
</script>	
<script type="text/javascript"
	src="<?php echo BASE_URL?>embeded/js/jquery.metadata.js">
</script>
<script type="text/javascript"
	src="<?php echo BASE_URL?>embeded/js/ColorPicker.js">
</script>

<script type="text/javascript" 	
		src="<?php echo BASE_URL?>embeded/js/jquery.validationEngine.js">
</script>
<?php echo $this->javascriptfile(BASE_URL."tools/script/get/file/".rawurlencode(rawurlencode(BASE_URL."embeded/js/jquery.validationEngine.langue.js")),false) ?>