<?php echo $this->javascriptfile(BASE_URL."embeded/js/jquery.facebox.js") ?>
<?php echo $this->javascriptfile(BASE_URL."embeded/js/jquery.blockUI.js") ?>
<?php echo $this->javascriptfile(BASE_URL."tools/script/get/file/".rawurlencode(rawurlencode(BASE_URL."embeded/js/jquery.validationEngine.langue.js")),false) ?>
<?php echo $this->javascriptfile(BASE_URL."embeded/js/jquery.validationEngine.js") ?>


<?php echo $this->cssfile( BASE_URL."themes/system/css/validationEngine.jquery.css") ?>

	
		<div  id="programlayout-video">		
				<div class="section">
        						<!--[if !IE]>start title wrapper<![endif]-->
        						<div class="title_wrapper clearfix">
        						
        							<h2><?php echo $this->_("Video files")?></h2>
        							<ul class="programToolBar">
        							 <?php if($this->_session->environment["module"] == "prod" || $this->_session->environment["module"] == "pub"):?>
        							<li>
        							<a href="javascript:void(0);" id="previewButton">
        								<img src="<?php echo BASE_URL?>themes/system/pics/video.png" title="<?php echo $this->_("preview") ?>"/>
        							</a>
        							</li>
        												<li>
        							<a href="javascript:void(0);" id="sendLinkButton">
        								<img src="<?php echo BASE_URL?>themes/system/pics/mail_generic.png" title="<?php echo $this->_("send link") ?>"/>
        							</a>
        							</li>
        							<?php endif;?>
        							<?php if($this->_session->environment["module"] == "prod"):?>
        							<li>
        							<a href="javascript:void(0);" id="btn_publishDefault" >
        								<img src="<?php echo BASE_URL?>themes/system/pics/publish.png" title="<?php echo $this->_("publish") ?>"/>
        							</a>
        							</li>
        							<?php endif;?>    
        							</ul>
        							
        						
        			
        							<span class="title_wrapper_left"></span>
        							
        						<span class="title_wrapper_right" style="display: block;"></span></div>
        						<!--[if !IE]>end title wrapper<![endif]-->
        						<!--[if !IE]>start section content<![endif]-->
        						<div class="section_content" id="programlayout-video">
        							<!--[if !IE]>start section content top<![endif]-->
        							<div class="sct">
        								<div class="sct_left">
        									<div class="sct_right">
        										<div class="sct_left">
        											<div class="sct_right">

        													<?php echo $this->naction("videozone","program","prod",array("key"=>$this->key,'fkey'=>$this->getParam("fkey","")))?>  
        													        													  
        													<?php if($this->_session->environment["module"] == "prod" || $this->_session->environment["module"] == "ser"):?>   																												
        													<div id="programlayout-video-addnew">
	        													<p align="center" class="class1">
	        													<?php echo $this->sexybutton ("href", $this->_("add new video"), array("add_new",""),  BASE_URL ."prod/program/addversions/key/".$this->key ,array()) ?>
	        													</p>
        													</div>
        													<div  id="programlayout-video-infosversions">
	        													<h3><?php echo $this->_("Details")?></h3>
	        													<div class="more_description">
	        													<?php  echo $this->naction("infosversions","program","prod",array("key"=>$this->key))?>
	        													</div>
        													</div>
        													<?php endif;?>
        											</div>
        										</div>
        									</div>
        								</div>
        							</div>
        							<!--[if !IE]>end section content top<![endif]-->
        							<!--[if !IE]>start section content bottom<![endif]-->
        							<span class="scb"><span class="scb_left"></span><span class="scb_right"></span></span>
        							<!--[if !IE]>end section content bottom<![endif]-->
        							
        						</div>
        						<!--[if !IE]>end section content<![endif]-->
                    </div>
		
		
		
		</div>
	
		<div  id="programlayout-edition">
		
        		<div class="section">
        						<!--[if !IE]>start title wrapper<![endif]-->
        						<div class="title_wrapper clearfix">
        							<h2><?php echo $this->_("Program form")?></h2>
		
        							<!--[if !IE]>start section menu<![endif]-->
        							<ul class="section_menu">
        							
        								<?php if($this->_session->environment["module"] == "prod" || $this->_session->environment["module"] == "ser"):?>
        								<li><a id="editinfo_action" href="<?php echo BASE_URL ?>prod/program/editinfo/key/<?php echo $this->key ?>"><span><span><?php echo $this->_("Description")?></span></span></a></li>
        			     				<li><a id="chapters_action"  href="<?php echo BASE_URL ?>prod/program/chapters/key/<?php echo $this->key ?>"><span><span><?php echo $this->_("Chapters")?></span></span></a></li>       								
        								<?php endif;?>
        								
        								
        								<?php if($this->_session->environment["module"] == "prod"):?>        								
                    								<?php if(($this->program["idprog_programs_extract"] == "" || $this->program["idprog_programs_extract"] == "0") ): ?>
                        								<?php if($this->program["state"] == "ACTIVATED" ):?>                        										
                        										<li><a id="extracts_action" href="<?php echo BASE_URL ?>prod/program/extracts/key/<?php echo $this->key ?>"><span><span><?php echo $this->_("Versions")?></span></span></a></li>
                        								<?php else:?>                        								
                        										<li><a id="extracts_action" href='javascript:alert("<?php echo $this->_("Please, you have to save your program before.")?>")'><span><span><?php echo $this->_("Versions")?></span></span></a></li>
                        								<?php endif;?>   
                                                    <?php endif;?>                                                    
                    								<?php if($this->program["state"] == "ACTIVATED" ):?>                     								                                                                								
                									<li><a id="publications_action" href="<?php echo BASE_URL ?>prod/program/publications/key/<?php echo $this->key ?>"><span><span><?php echo $this->_("Syndication")?></span></span></a></li>                									              
        									       	<?php if($this->_session->environment["details"]["idservice"] > 0):?>
													<!-- <li><a  title="<?php echo $this->_("Order services")?>" href=""><img src="<?php echo BASE_URL ?>themes/system/pics/configure.png" /></a></li> -->
													<li><a id="services_action" href="<?php echo BASE_URL ?>ser/prod/list/key/<?php echo $this->key ?>/programTitle/<?php echo urlencode(urlencode($this->program["details"]["title"]["value"])) ?>/idprog/<?php echo $this->program["idprog"] ?>"><span><span><?php echo $this->_("Services")?></span></span></a></li>
                                                    <?php endif;?>                									                								
                									<li><a id="programstatsoverview_action" href="<?php echo BASE_URL ?>prod/program/programstatsoverview/key/<?php echo $this->key ?>/idprog/<?php echo $this->program["idprog"] ?>"><span><span><?php echo $this->_("Statistics")?></span></span></a></li>
                									<?php else:?>
                									<li><a id="publications_action" href='javascript:alert("<?php echo $this->_("Please, you have to save your program before.")?>")'><span><span><?php echo $this->_("Syndication")?></span></span></a></li>
                									<li><a id="programstatsoverview_action" href='javascript:alert("<?php echo $this->_("Please, you have to save your program before.")?>")'><span><span><?php echo $this->_("Statistics")?></span></span></a></li>
                    								<?php endif;?>
        								<?php endif; ?>

        								
        								
        								<?php if($this->_session->environment["module"] == "pub"):?>
            									<li><a id="editinfo_action" href="<?php echo BASE_URL ?>pub/stock/manage/key/<?php echo $this->key ?>/fkey/<?php echo $this->fkey ?>/view/<?php echo $this->currentidview?>/publicationKey/<?php echo $this->getParam("publicationKey",$this->_session->environment["details"]["key"])?>"><span><span><?php echo $this->_("Description")?></span></span></a></li>
            									<li><a id="chapters_action"  href="<?php echo BASE_URL ?>pub/stock/editchapters/key/<?php echo $this->key ?>/fkey/<?php echo $this->fkey ?>/view/<?php echo $this->currentidview?>/publicationKey/<?php echo $this->getParam("publicationKey",$this->_session->environment["details"]["key"])?>"><span><span><?php echo $this->_("Chapters")?></span></span></a></li>
            									<?php if(($this->program["idprog_programs_extract"] == "" || $this->program["idprog_programs_extract"] == "0") &&  $this->program["state"] == "ACTIVATED" ): ?>
            									<li><a id="extracts_action" href="<?php echo BASE_URL ?>pub/stock/extracts/key/<?php echo $this->key ?>/fkey/<?php echo $this->fkey ?>/view/<?php echo $this->currentidview?>/publicationKey/<?php echo $this->getParam("publicationKey",$this->_session->environment["details"]["key"])?>"><span><span><?php echo $this->_("Versions")?></span></span></a></li>
            									<?php endif;?>
        											<?php if($this->_session->environment["details"]["idservice"] > 0):?>
                									<li><a id="services_action" href="<?php print BASE_URL ?>ser/prod/list/fkey/<?php echo $this->fkey ?>/programTitle/<?php echo urlencode(urlencode($this->program["details"]["title"]["value"])) ?>/idprog/<?php echo $this->program["idprog"]?>/publicationKey/<?php echo $this->_session->environment["details"]["key"] ?>"><span><span><?php echo $this->_("Services")?></span></span></a></li>
                									<?php endif;?>
            									<li><a id="programstatsoverview_action" href="<?php echo BASE_URL ?>pub/stock/programstatsoverview/key/<?php echo $this->key ?>/idprog/<?php echo $this->program["idprog_programs_of"] ?>/fkey/<?php echo $this->fkey ?>/view/<?php echo $this->currentidview?>/publicationKey/<?php echo $this->getParam("publicationKey",$this->_session->environment["details"]["key"])?>"><span><span><?php echo $this->_("Statistics")?></span></span></a></li>
        								<?php endif; ?>
        								
        								

        							</ul>
        							        	        										
        							        			
        							        	<?php if($this->program["state"] != "CREATION"):?>			
        
                                                        <?php if($this->_session->environment["module"] == "pub"):?>
                										<ul class="programToolBar">      
                													<?php
																	$session = Zend_Registry::get("session");
																	if(isset($session->user->access)){
																	    for($i=0;$i<sizeof($session->user->access);$i++){
																	        if($session->user->access[$i]["module"] == "prod" && $session->user->access[$i]["ressource"] ==  $this->programReview[0]["idproduction"] && $session->user->access[$i]["level"] == 0): ?>
														
																		<li><a  title="Production : <?php echo $this->_("re-edit") ?>"  href="javascript:setEnvironment('<?php echo $session->user->access[$i]["tmpaccess"] ?>', '<?php echo BASE_URL ?>prod/program/editinfo/key/<?php echo $this->fkey?>')"><img  src="<?php echo BASE_URL ?>themes/system/pics/edit.gif" /></a></li>
																			<?php endif;
																	    }
																	}
																	?>
			          										
                											<li><a  title="<?php echo $this->_("Integration")?>" href="<?php echo BASE_URL ?>pub/integration/program/key/<?php echo $this->key ?>"><img  src="<?php echo BASE_URL ?>themes/system/pics/integration.png" /></a></li>                                                        		                                                        			                                                
        													<li><a  title="<?php echo $this->_("Export program")?>" href="<?php echo BASE_URL ?>pub/data/exportprogram/keyprog/<?php echo $this->key ?>/viewcode/<?php echo Zend_Controller_Front::getInstance()->getRequest()->getParam("viewcode","default") ?>/publicationKey/<?php echo $this->_session->environment["details"]["key"] ?>"><img  src="<?php echo BASE_URL ?>themes/system/pics/export.png" /></a></li>        													        													
                                                            <?php if($this->_session->environment["details"]["idservice"] > 0):?>
        													<!-- <li><a  title="<?php echo $this->_("Order services")?>" href="<?php print BASE_URL ?>ser/prod/list/fkey/<?php echo $this->fkey ?>/programTitle/<?php echo urlencode(urlencode($this->program["details"]["title"]["value"])) ?>/idprog/<?php echo $this->program["idprog"]?>/publicationKey/<?php echo $this->_session->environment["details"]["key"] ?>"><img src="<?php echo BASE_URL ?>themes/system/pics/configure.png" /></a></li> -->
        													<?php endif;?>
        																										                                                		
                                            			</ul>
                                            			<?php endif;?>
                                            			
        												<?php if($this->_session->environment["module"] == "prod"):?>
                										<ul class="programToolBar">  
                										    
                										    <?php if(($this->program["idprog_programs_extract"] == "" || $this->program["idprog_programs_extract"] == "0") ): ?>
															<li><a id="consoledirect" href="<?php echo BASE_URL ?>prod/direct/console/key/<?php echo $this->key ?>" title="<?php echo $this->_("Live")?>"><img  src="<?php echo BASE_URL ?>themes/system/pics/logo_direct.png" /></a></li>
															<?php endif;?>                										                                                      		                                                        			
                                                        	<li><a id="duplicateprogram" href="<?php echo BASE_URL ?>prod/program/duplicate/key/<?php echo $this->key ?>" title="<?php echo $this->_("Duplicate program")?>"><img  src="<?php echo BASE_URL ?>themes/system/pics/duplicate.png" /></a></li>
                                                            <?php if($this->replication ):?>
        													<li><a title="<?php echo $this->_("Internet replication")?>" id="replicationLink" href="<?php echo BASE_URL ?>prod/tools/replicate/key/<?php echo $this->key ?>"><img  src="<?php echo BASE_URL ?>themes/system/pics/duplicate.gif" /></a></li>
                                                            <?php endif;?>
        													<li><a  title="<?php echo $this->_("Export program")?>" href="<?php echo BASE_URL ?>prod/data/exportprogram/keyprog/<?php echo $this->key ?>"><img  src="<?php echo BASE_URL ?>themes/system/pics/export.png" /></a></li>
                                                            <?php if($this->_session->environment["details"]["idservice"] > 0):?>
        														<!-- <li><a  title="<?php echo $this->_("Order services")?>" href="<?php echo BASE_URL ?>ser/prod/list/key/<?php echo $this->key ?>/programTitle/<?php echo urlencode(urlencode($this->program["details"]["title"]["value"])) ?>/idprog/<?php echo $this->program["idprog"] ?>"><img src="<?php echo BASE_URL ?>themes/system/pics/configure.png" /></a></li> -->
                                                            <?php endif;?>
        													<li><a  title="<?php echo $this->_("Delete program")?>" id="deleteprogram" href="<?php echo BASE_URL?>prod/program/delete/keyToDelete/<?php print $this->key?>"><img  src="<?php echo BASE_URL ?>themes/system/pics/pics/png/no.png" /></a></li>		
                                            			</ul>
                                            			<?php endif;?>
                                    			
                                    			<?php endif;?>
                                    			
                                    
        							<!--[if !IE]>end section menu<![endif]-->
        							
        							
        							<span class="title_wrapper_left"></span>
        							
        						<span class="title_wrapper_right" style="display: block;"></span></div>
        						<!--[if !IE]>end title wrapper<![endif]-->
        						<!--[if !IE]>start section content<![endif]-->
        						<div class="section_content" id="programlayout-content">
        							<!--[if !IE]>start section content top<![endif]-->
        							<div class="sct">
        								<div class="sct_left">
        									<div class="sct_right">
        										<div class="sct_left">
        											<div class="sct_right">
        											
        												
        												<div class="subcontainer">
        												<?php if($this->_session->environment["module"] == "pub" || ($this->_session->environment["module"] == "ser"  && $this->getParam("module") == "pub")):?>
        												<p><?php $tmp = array(); foreach ($this->views as $view):    	
                                                            $tmp[ $view["viewcode"] ] = $view["viewname"];
                                                            endforeach;?> <?php echo $this->_("Views")?> : <?php echo $this->formSelect("viewSelector", Zend_Controller_Front::getInstance()->getRequest()->getParam("viewcode","default") ,null,$tmp) ?>
														</p>
														
														<script type="text/javascript">

															jQuery(document).ready(function(){

																
																$("#viewSelector").change(function(){		
																	document.location.href = "<?php echo BASE_URL ?>pub/stock/manage/fkey/<?php echo $this->fkey ?>/viewcode/"+$("#viewSelector").val() + "/publicationKey/<?php echo $this->getParam("publicationKey",$this->_session->environment["details"]["key"])?>";
																});
																
																
																
															});
														
														</script>
														<?php endif;?>
													
														<div id="programlayout-program-title">
														<h3 class="fixed"><?php echo  isset($this->program["details"]["title"]) ? ( $this->program["details"]["title"]["value"]) : ""?>
																											
                                                        <?php if($this->_session->environment["module"] == "prod"):?>
            								                <?php if($this->program["idprog_programs_extract"] >0 ): ?>
                                                           		 (<?php echo $this->_("Extract of")?>: <a	href="<?php echo BASE_URL?>prod/program/manage/key/<?php echo $this->programFrom["keyprog"] ?>"><?php echo $this->programFrom["details"]["title"]["original_value"]?></a>)
                                                            <?php endif;?>
                                                        <?php endif;?>                                                        
														</h3>
														<?php 
														
														if(Model_Program::getDirectState($this->program["idprog"])){
															echo $this->SystemMessage($this->_("Becarefull, this program is under direct"),2);
														}
																											
														?>
														</div>
														<div id="programlayout-program-content">
														<?php 
														//echo $this->layout()->content 
														 echo $this->block('content'); 
														?>
        												</div>
        												
        												
        												</div>

                                                        
        											</div>
        										</div>
        									</div>
        								</div>
        							</div>
        							<!--[if !IE]>end section content top<![endif]-->
        							<!--[if !IE]>start section content bottom<![endif]-->
        							<span class="scb"><span class="scb_left"></span><span class="scb_right"></span></span>
        							<!--[if !IE]>end section content bottom<![endif]-->
        							
        						</div>
        						<!--[if !IE]>end section content<![endif]-->
                    </div>
		
		</div>
	





<script type="text/javascript">


	jQuery(document).ready(function(){
		
		$("#<?php echo $this->current_action ?>_action").addClass("active");
	
		    <?php if($this->progPublish instanceof Model_Program):?>
    		$("#previewButton").click(function(){
    			<?php if($this->_session->environment["module"] == "prod"):?>				
    			jQuery.ajax({
    				type:'get',
    				url : '<?php echo BASE_URL?>prod/program/updatepublishing/keyprog/<?php echo $this->key ?>',
    				success : function(msg){showPreview();}				
    			});	
    			<?php endif;?>	
    			<?php if($this->_session->environment["module"] == "pub"):?>	
    			showPreview();
    		    <?php endif;?> 						             			
    		});	
    		
    		$("#sendLinkButton").click(function(){
    			<?php if($this->_session->environment["module"] == "prod" || $this->_session->environment["module"] == "pub"):?>	
				     var url = "http://<?php echo $_SERVER["HTTP_HOST"] ?><?php echo $this->url(array("module"=>"watch","controller"=>"webtv","action"=>"lecteurvideo","key"=>$this->progPublish->publicationkey,"id"=>$this->progPublish->keyprog,"lang"=>$this->_session->locale,"type"=>"pr"),null,true)  ?>";		
   			     <?php endif;?>
    		    window.open( "mailto:?body=" + url );				             			
    		});	
    		
    		
    		function showPreview(){   
    			svlObjectDialog.Content.SilverlightApp.pausePlayer();	
    			$.facebox.settings.opacity = 0.6; 	
    			<?php $previewParams = array("width"=>"450","height"=>"338","culture"=>$this->_session->locale) ; if(isset($this->viewlocale)) $previewParams["lang"]= $this->viewlocale;?>
    			$.facebox('<?php echo preg_replace("#\r\n#","",$this->progPublish->getIframeEmbedSilverlightCode($previewParams)) ?>',"clean");			
    		}

    		<?php else:?>
    		$("#previewButton").click(function(){
				alert("<?php echo $this->_("Problem with this production account, no publication associated !","none") ?>")
    		});
		<?php endif;?>
		
		

		


		<?php if($this->_session->environment["module"] == "prod" && $this->defaultIdPub > 0):?>

		$("#btn_publishDefault").click(function(){
			$.ajax({
				type:"post",
				url:"<?php echo BASE_URL ?>prod/program/dispo",
				data:{key:"<?php echo $this->key ?>",id:"checkPublication_<?php echo $this->defaultIdPub ?>",state:"true"},
				success:function(msg){
					alert("<?php echo $this->_("Done !","none") ?>");
				}
			});
		});

		<?php endif;?>


		  var _destroyUrl;    	
		    $('#deleteprogram').click(function() {
		    	$('#dialogdelete').dialog('open');
		    	_destroyUrl = $(this).attr("href");
		    	return false;
		    });
		    
		$("#dialogdelete").dialog({
			
			bgiframe: true,
			width:550,
			
			modal: true,
			autoOpen:false,
			overlay: {
				backgroundColor: '#000',
				opacity: 0.5
			},
			buttons: {
				'<?php echo $this->_("Delete")?>': function() {
					$(this).dialog('close');
					var url = _destroyUrl + "/deletefile/" + (jQuery("#dialogdelete.ui-dialog-content input[name=deletefile]:checked").val() );		
					document.location.href = url;
									
				},
				<?php echo $this->_("Cancel")?>: function() {
					$(this).dialog('close');
				}
			}
		});


		 $("#replicationLink").click(function(event){$("#dialogReplication").dialog('open');event.preventDefault();});
		 $("#duplicateprogram").click(function(event){$("#dialogDuplication").dialog('open');event.preventDefault();});

		    $("#dialogReplication").dialog({			
				bgiframe: true,					
				modal: true,
				autoOpen:false,
				overlay: {
					backgroundColor: '#000',
					opacity: 0.5
				},
				buttons: {
					'<?php echo $this->_("Replicate this program","none")?>': function() {
						$(this).dialog('close');
						$.blockUI({message:"<h1><?php echo $this->_("Please wait") ?></h1>"});
						$.ajax({
							type:'get',
							url : $("#replicationLink").attr("href"),
							success : function(msg){
							if(msg == "ok")
								alert("<?php echo $this->_("Successfull replication  for data. Video files will be deployed over the next cron job.","none"); ?>");
							else
								alert(msg);						
							},
							error : function(){
								alert("<?php echo $this->_("Problem during data replication"); ?>");
							},
							complete : function(){
								$.unblockUI();
							}
						});		
															
					},
					<?php echo $this->_("Cancel")?>: function() {
						$(this).dialog('close');
					}
				}
			});
		    $("#dialogDuplication").dialog({			
				bgiframe: true,					
				modal: true,
				autoOpen:false,
				overlay: {
					backgroundColor: '#000',
					opacity: 0.5
				},
				buttons: {
					'<?php echo $this->_("Duplicate this program")?>': function() {
						$(this).dialog('close');
						document.location.href = $("#duplicateprogram").attr("href");
						}																				
					,
					<?php echo $this->_("Cancel")?>: function() {
						$(this).dialog('close');
					}
				}
			});
			
			
	});

</script>
<?php if($this->_session->environment["module"] == "pub"):?>
<?php echo $this->naction("checkupdates","stock","pub",array("idprogramFrom"=>$this->program["idprog_programs_of"])); ?>
<?php endif;?>



<div id="dialogdelete" title="<?php echo  $this->_("Removal confirmation") ?>">
<form method="post" action="<?php echo BASE_URL ?>prod/program/delete"	id="formProgramToDelete">
<p><span class="ui-icon ui-icon-alert"	style="float: left; margin: 0 7px 20px 0;"></span> <?php echo  $this->_("This program will be deleted. Are you sure ?") ?>

<input type="hidden" id="keyToDelete" name="keyToDelete" value="tata" />

</p>
<p><?php echo $this->_("Delete file on server : ") ?> </p>

<ul>
	<li><input type="radio" name="deletefile" value="true" /><?php echo $this->_("Delete")?></li>
	<li><input type="radio" name="deletefile" value="false" checked="checked" id="mustdeletefile" /><?php echo $this->_("Restore to depot")?></li>
	<li><input type="radio" name="deletefile" value="keep" /><?php echo $this->_("Keep at the same place")?></li>
</ul>
</form>
</div>



<div id="dialogReplication" title="<?php echo  $this->_("Program replication") ?>">
	<p>
		<?php echo $this->_("Your are going to replicate this program to internet.")?>
	</p>
</div>

<div id="dialogDuplication" title="<?php echo  $this->_("Program duplication") ?>">
	<p>
		<?php echo $this->_("Your are going to duplicate this program.")?>
	</p>
</div>

<?php if($this->_session->environment["module"] == "prod" && $this->program["state"] != "CREATION" ):?> 
<?php if(($this->program["idprog_programs_extract"] == "" || $this->program["idprog_programs_extract"] == "0") ): ?>
<script type="text/javascript">

Ext.onReady(function() {		    
	
	Ext.get("consoledirect").on("click",function(){
		new Ext.Window({
		    title : "<?php echo $this->_("Live console","javascript") ?>",
		    width : 1280,
		    height: 800,
		    constrain:true,
		    id:"directconsolewindow",
		    modal:true,
		    layout : 'fit',
		  	items:[{
		  		 xtype : "component",
		         autoEl : {
		             tag : "iframe",
		             src : Ext.getDom("consoledirect").href
		         }
			}]
		}).show();		
	},null,{preventDefault :true}); 
});
/*[new Ext.ux.IFrameComponent({ id: "frameconsoledirect", url: Ext.getDom("consoledirect").href })] */
</script>
<?php endif;?>
<?php endif;?>


<script type="text/javascript">
function setEnvironment(environmentID,uri){
	document.location.href = BASE_URL + "default/environment/setenvir/ressourceSelector/" + environmentID + "?uri=" + uri;	
}
</script>
