<html>
<head>

<style>

body{
background: none repeat scroll 0 0 #161613 ;
font:86% 'Lucida Grande','Lucida Sans Unicode',Verdana,sans-serif;
color:#EEEEEE;
}
ul{
	list-style:none;
}
img{
	border:none;
}
a:link, a:hover, a:visited{
	color:#C0DB5A;
	text-decoration: none;
}
</style>

</head>
<body>

</body>
</html>
<p>

	<?php echo $this->_("Your browser is not supported.")?><br/>
	<?php echo $this->_("Please, use a more recent browse version.")?>

</p>

<ul>

	<li><a href="http://www.google.com/chrome/" title="google chrome">Google Chrome</a></li>
	<li><a href="http://www.mozilla-europe.org" title="Mozilla Firefox">Mozilla Firefox</a></li>
	<li><a href="http://www.microsoft.com/france/windows/internet-explorer/" title="Internet Explorer">Internet Explorer</a></li>
	<li><a href="http://www.opera.com" title="Opera">Opera</a></li>

</ul>

<p>
	<?php echo $this->_("Thank you for your understanding.")?>
</p>