<?php
echo $this->javascriptfile ( BASE_URL . "tools/script/get/file/" . rawurlencode ( rawurlencode ( BASE_URL . "embeded/js/jquery.validationEngine.langue.js" ) ), false )?>
<script type="text/javascript"
	src="<?php
	echo BASE_URL?>embeded/js/jquery.validationEngine.js"></script>
<?php
echo $this->cssfile ( BASE_URL . "themes/system/css/validationEngine.jquery.css" )?>
<script type="text/javascript"
	src="<?php
	echo BASE_URL?>embeded/js/jquery.meio.mask.js"></script>


<?php
$this->placeholder ( "title" )->set ( $this->_ ( "Edit a production account" ) )?>

<form method="post"
	action="<?php
	echo BASE_URL?>sadmin/productions/update"
	id="productionForm">

<fieldset>


<p><label><?php
echo $this->_ ( "Name" )?></label> <span><?php
echo $this->formText ( "name", "", array ("class" => "validate[required]" ) )?></span>
</p>

<p><label><?php
echo $this->_ ( "Alias" )?></label> <span><?php
echo $this->formText ( "alias", "", array ("class" => "validate[required,custom[noSpecialCaracters]]", null ) )?></span>
</p>

<p><label><?php
echo $this->_ ( "Organization" )?></label> <span><?php
echo $this->formSelect ( "idorganization", "", array ("class" => "validate[required]" ), $this->organizationsList )?></span>
</p>

<p><label><?php
echo $this->_ ( "Email" )?></label> <span><?php
echo $this->formText ( "email", "", null )?></span></p>
<p><label><?php
echo $this->_ ( "Email 2" )?></label> <span><?php
echo $this->formText ( "email2", "", null )?></span></p>
<p><label><?php
echo $this->_ ( "Phone number" )?></label> <span><?php
echo $this->formText ( "phonenumber2", "", null )?></span></p>
<p><label><?php
echo $this->_ ( "Mobile phone" )?></label> <span><?php
echo $this->formText ( "mobilephone", "", null )?></span></p>
<p><label><?php
echo $this->_ ( "Organization" )?></label> <span><?php
echo $this->formSelect ( 'organization', 2, null, $this->contentTable ( "enum_organization" ) );
?></span></p>
<p><label><?php
echo $this->_ ( "Organization details" )?></label> <span><?php
echo $this->formSelect ( 'organization_details', 2, null, $this->contentTable ( "enum_organization2" ) );
?></span></p>
<p><label><?php
echo $this->_ ( "Notes" )?></label> <span><?php
echo $this->formTextarea ( "notes", "", null )?></span></p>
<p><label><?php
echo $this->_ ( "Picture" )?></label> <span><?php
echo $this->formText ( "picture", "", null )?>
	<a href="javascript:filemanager('picture');"
	title="<?php
	echo $this->_ ( "File explorer" )?>"> <img
	src="<?php
	echo BASE_URL?>themes/system/pics/explorer.png"
	class="icones" /> </a> </span></p>


<div style="display: none">
<p><label><?php
echo $this->_ ( "Title" )?></label> <span><?php
echo $this->formText ( "title", "", null )?></span></p>
<p><label><?php
echo $this->_ ( "Work" )?></label> <span><?php
echo $this->formText ( "work", "", null )?></span></p>
</div>

<p><label><?php
echo $this->_ ( "Service" )?></label> <span><?php
echo $this->formSelect ( "idservice", "", null, $this->servicesList )?></span>


<p>
	<label><?php echo $this->_ ( "Profile" )?></label>
	<span><?php echo $this->formSelect ( "idprofil", "", null, $this->SimpleTable ( "encoding_profils", "", "idprofil", "title" ) )?></span>
</p>
<p>
	<label><?php echo $this->_("Broadcaster") ?></label>
	<span><?php echo $this->formSelect("broadcaster", "" ,null,$this->broadcasters) ?></span>
	<?php echo $this->formHidden ( "streamercode", $this->rawData ['broadcaster']['streamercode'], null )?>
</p>
	
<!-- 
	<p>
		<label><?php echo $this->_ ( "Group of fields" )?></label>
		<span><?php echo $this->formSelect ( "idgroup", "", null, $this->groupList )?></span>
	</p>
-->
<div style="display: none">
<p>
	<label><?php echo $this->_ ( "Text banner" )?></label>
	<span><?php echo $this->formTextarea ( "textbandeau", "", array ("cols" => 50, "rows" => 10 ) )?></span>
</p>
</div>
<p>
	<label><?php echo $this->_ ( "Watermark" )?></label>
	<span><?php echo $this->formTextarea ( "textwatermark", "", array ("cols" => 50, "rows" => 10 ) )?></span>
</p>

<p>
	<label><?php echo $this->_ ( "Copyright" )?></label>
	<span><?php echo $this->formTextarea ( "textcopyright", "", array ("cols" => 50, "rows" => 10 ) )?></span>
</p>


<p>
	<label><?php echo $this->_ ( "Key" )?></label>
	<span><?php echo $this->formText ( "key", "", array ("disabled" => "disabled" ) )?></span>
</p>

<p>
	<label><?php echo $this->_ ( "Path download" )?></label>
	<span><?php echo $this->formText ( "pathdownload", "", array ("disabled" => "disabled" ) )?></span>
</p>
<p>
	<label><?php echo $this->_ ( "Path pictures" )?></label>
	<span><?php echo $this->formText ( "pathpictures", "", array ("disabled" => "disabled" ) )?></span>
</p>
<p>
	<label><?php echo $this->_ ( "Depot directory" )?></label>
	<span><?php echo $this->formText ( "depositdirectory", "", array ("disabled" => "disabled" ) )?></span>
</p>
<p>
	<label><?php echo $this->_ ( "Streaming directory" )?></label>
	<span><?php echo $this->formText ( "streamdirectory", "", array ("disabled" => "disabled" ) )?></span>
</p>
<p>
	<label>&nbsp; <?php echo $this->formHidden ( "idproduction", $this->idproduction, null )?></label>	
	<span ><a id="mms-dialog"  href="#"><?php echo $this->_ ( "MMS Update" );?></a></span>
</p>
<p>
	<label>&nbsp;</label>
	<span> <?php echo $this->sexybutton ( "submit", $this->_ ( "save" ), array ("send_form_btn" ), null )?></span>	

</p>
<div class="clear"></div>
</fieldset>
</form>

<!-- MMS Update dialog starts here -->
<div id="mms-update-form" title="<?php echo $this->_ ( "Update mms" );?>">
	<div id="result"></div>
	<form id="mms_update" method="post" action="<?php echo $this->url ( array ("module" => "sadmin", "controller" => "mms", "action" => "update" ), null, true )?>">
		<?php echo $this->formHidden ( "page", "2" ); ?>
		<div class="form-bloc">
			<p><label for="old_mms"><?php echo $this->_ ( "String in mms to replace" )?></label></p>
			<p>
				<?php
					echo $this->formText ( "old_mms", $this->uris[0], array ("size" => "32" ) );
				?>
			</p>
		</div><!--  MMS old value stored in broadcast.ini-->
		<div class="form-bloc">
			<p><label for="new_mms"><?php echo $this->_ ( "String replacement" )?></label></p>
			<p>
				<?php
				echo $this->formHidden ( "idprod", $this->rawData ['idproduction'] );
				echo $this->formHidden ( "scode", $this->rawData ['streamercode'] );
				?>
				<?php
				echo $this->formText ( "new_mms", "", array ("autofocus" => "on", "size" => "32", "required" => "required", "placeholder" => $this->_ ( "Enter new value" ) ) );
				?>
				<span id="info-mms"></span>
			</p>
		</div><!--  MMS new value set by user-->
		<div class="form-bloc">
			<h3><?php echo $this->_ ( "Apply to " )?></h3>
			<p>
				<label class="span3" for="prod1"><?php echo $this->_ ( "Current account" )?>
					<input id="prod1" type="radio" value="1" name="prod" checked="checked" />
				</label>
				<label class="span3" for="prod2"><?php echo $this->_ ( "all productions" )?>
					<input id="prod2" type="radio" value="2" name="prod" />
				</label>
			</p>
		</div>
	</form>
</div>
<!-- <div id="debug"></div>  -->
<!-- MMS Update dialog ends here -->

<div id="divIdExplorer" title="<?php echo $this->_ ( "Explorer" );?>">
	<iframe id="modalIframeIdExplorer" width="100%" height="95%" src="" marginWidth="0" marginHeight="0" frameborder="0" scrolling="auto">
	Your browser does not suppr
	</iframe>
</div>


<script type="text/javascript">
//<![CDATA[   

var $currentField ;
function filemanager(idref)
{		
	$currentField = jQuery("#"+idref);		
	jQuery("#modalIframeIdExplorer").attr("src","<?php
	echo BASE_URL?>tools/filemanager/explorer");	
	jQuery("#divIdExplorer").dialog('open');
}

jQuery(document).ready(function(){   
	$.metadata.setType("attr", "metadata");
	$("#pictureZone").click(function(){
    	$("#loadPicture").dialog('open');	
	});
	$("#divIdExplorer").dialog({
    	modal: false,
    	autoOpen: false,    	        
    	width:960,
    	height:615,	    	
    	buttons: {
    			'<?php
							echo $this->_ ( "Select", "none" )?>':function(){
            		var filesSelected = new Array();
            		$('#modalIframeIdExplorer').contents().find('#explorerPanel .clicked').parent().each(function(){					            		
            			filesSelected.push($(this).metadata().link);			            						
            		});      	                 		   				
            		for(var i=0;i<filesSelected.length;i++){                     		  		
            			$currentField.val(filesSelected[i]);            			 
            		}
    				$(this).dialog('close');  					
    			},						
    			'<?php
							echo $this->_ ( "Cancel" )?>':function(){
    					$(this).dialog('close');
    				}
    			}
    });	
		 
});
//]]>
</script>

<script type="text/javascript">
//<![CDATA[   
var field_not_ok = [<?php
echo $this->field_not_ok?>];
jQuery(document).ready(function(){     
	   $("#productionForm").validationEngine();  
    jQuery.each(field_not_ok, function() {
      $("#" + this).addClass("input_nok");
    }); 
    $('input:text').setMask(); 
    <?php
		foreach ( $this->rawData as $key => $value ) :
		 ?>
				$("#<?php echo $key?>").val('<?php echo $this->escape ( $value );?>');					
			<?php 
				endforeach
		;?>
});
//]]>
</script>
<script type="text/javascript">
$(document).ready(function() {
	$('#mms-dialog').click(function() {
		$dialog.dialog('open');
		// prevent the default action, e.g., following a link
		return false;
	});
	var $dialog = $('#mms-update-form')
		.dialog({
			autoOpen: false,
			width:530,
			buttons: {
				"<?php echo $this->_("Cancel") ?>": function() {
					$("#new_mms").val("");
					$("#result").empty();
					$(this).dialog("close");
				},
				"<?php echo $this->_("Save") ?>": function() {
					$("#mms_update").submit();
				}
			},
			close:function(event, ui) { $("#new_mms").val(""); $("#result").empty();$("#info-mms").empty()}	
		});
});
</script>

<script>
//Check for correct mms value
$('#mms_update input:text').keyup(function(){
	$("#info-mms").fadeIn().empty().html('<span class="alert alert-error"><?php echo $this->_("Please, write a valid MMS.") ?></span>');
	$(this).filter(function() {
        return this.value.match(/^[a-zA-Z]+:\/\/([a-zA-Z0-9]{1,}\.){1,}.*/g);// Looks for uri that starts with : "protocol://x.y". Eg: "mms://12."
    }).parent().find("#info-mms").empty().html('<span class="alert alert-success"><?php echo $this->_("Thank you !") ?></span>');
});

// Throws submit event !
$("#mms_update").submit(function(event) {

	if($("#new_mms").val() =='' || $("#old_mms").val()=='') {
		$("#result").html('<div class="alert alert-error"><p><strong><h3><?php echo $this->_("Error !") ?></h3></strong><?php echo $this->_("Please, write a correct new value.") ?>');
		 return false;
	}
	event.preventDefault();
	$("#result").html('<img src="<?php echo BASE_URL?>themes/liquid/css/layout/site/forms/loading.gif"; />');

	url = $(this).attr( 'action' );
	var data = $(this).serialize();
	$.ajax({
		  type: 'POST',
		  url: url,
		  data: data,
		  success: function(){
			  $("#info-mms").fadeOut();
			  $("#result").empty().html('<div class="alert alert-success"><p><?php echo $this->_("Update process finished correctly !") ?></p> <p><br />'+$("#old_mms").val()+' &rarr; '+$("#new_mms").val()+'</p></div>');
			  }
		});
});
</script>