<script type="text/javascript">

var gcv_popup_width = 320;
var gcv_popup_height = 240;
var gcv_dualscreen = 1;
var gcv_currentchapter = 1;
var gcv_autoplay=0;
var gcv_button = "1011110111111";
var gcv_lang = "<?php echo $this->locale ?>";

function gcv_loadUrl(url){
url = url + "?width=" + gcv_popup_width + "&height=" +gcv_popup_height + "&dualscreen=" + gcv_dualscreen + "&button=" + gcv_button+"&culture=" + gcv_lang+"&currentChapterDisplay="+gcv_currentchapter+"&autoplay="+gcv_autoplay;
var top=(screen.height-gcv_popup_height)/2;
var left=(screen.width-gcv_popup_width)/2;
window.open(url,"","WIDTH=" + gcv_popup_width +",HEIGHT=" + gcv_popup_height + ",left=" +left+ ",top="+top);
}

</script>
<a href="javascript:void(0);" onclick="gcv_loadUrl('<?php echo  $this->playlist->getSilverlightUrl() ?>')"><?php echo  $this->playlist->title ?>&nbsp;
<img src="http://<?php echo $_SERVER["HTTP_HOST"]?><?php echo BASE_URL ?>themes/system/pics/cam.gif" height="20px" width="20px" align="top" alt="" border="0" />
</a>
