<a href="javascript:void(0);"
onclick="gcv_loadUrl('<?php echo  $this->playlist->getHtmlUrl() ?>')">
<?php echo $this->playlist->title ?>&nbsp;<img src="http://<?php echo  $_SERVER["HTTP_HOST"]?><?php echo BASE_URL ?>themes/system/pics/cam.gif"
height="20px" width="20px" align="top" alt="" border="0" /> </a>
<script type="text/javascript">

var gcv_popup_width = 330;
var gcv_popup_height = 520;



function gcv_loadUrl(url){
var top=(screen.height-gcv_popup_height)/2;
var left=(screen.width-gcv_popup_width)/2;
window.open(url,"","WIDTH=" + gcv_popup_width +",HEIGHT=" + gcv_popup_height + ",left=" +left+ ",top="+top+",dependent");
}       

</script>
