<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta http-equiv="imagetoolbar" content="no" />
<title><?php echo $this->_config["productname"]?> : <?php echo $this->_("Connection") ?></title>
<?php echo $this->cssfile( BASE_URL."themes/liquid/css/admin-login.css") ?>
<?php echo $this->cssfile( BASE_URL."themes/liquid/css/gcv.css") ?>
<?php echo $this->cssfile( BASE_URL."themes/system/css/facebox.css") ?>

<!--[if lte IE 6]><?php echo $this->cssfile( BASE_URL."themes/liquid/css/admin-login-ie.css") ?><![endif]-->

<script type="text/javascript">var BASE_URL = "<?php echo BASE_URL?>";</script>
<?php echo $this->javascriptfile( BASE_URL."embeded/js/jquery-1.4.2.min.js") ?>
<?php echo $this->javascriptfile( BASE_URL."embeded/js/jquery-ui-1.8.5.custom.min.js") ?>

<?php 
$this->headScript()->appendFile(BASE_URL.'embeded/js/jquery.facebox.js');
echo $this->headScript()
?>

<?php echo $this->javascriptfile(BASE_URL."tools/script/get/file/".rawurlencode(rawurlencode(BASE_URL."embeded/js/jquery.validationEngine.langue.js")),false) ?>
<?php echo $this->javascriptfile(BASE_URL."embeded/js/jquery.validationEngine.js") ?>
<?php echo $this->cssfile( BASE_URL."themes/system/css/validationEngine.jquery.css") ?>

</head>

<body>
	<!--[if !IE]>start wrapper<![endif]-->
	<div id="wrapper">
	
		<!--[if !IE]>start login wrapper<![endif]-->
		<div id="login_wrapper">
			
		
		<?php 
		    echo $this->layout()->content;
		?>

		</div>
		<!--[if !IE]>end login wrapper<![endif]-->
	</div>
	<!--[if !IE]>end wrapper<![endif]-->
	
	<script type="text/javascript">
		jQuery(document).ready(function(){			
			
		});	
	</script>
	
</body>
</html>



