<!doctype html>
<html>
<head>
<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
<?php $this->headTitle(  $this->placeholder("title") ) ->setSeparator(" - ")->prepend($this->_config["productname"]);   ?>
<script type="text/javascript">var BASE_URL = "<?php echo BASE_URL?>";</script>
<?php echo $this->javascriptfile( array(
	BASE_URL."embeded/packs/extjs/ext-all.js",
	BASE_URL."embeded/js/extjs_override.js",	
	BASE_URL."embeded/js/jquery-1.4.2.min.js",
	BASE_URL."embeded/js/jquery-ui-1.8.5.custom.min.js",
	BASE_URL."embeded/js/jquery.formStyle.js",
	BASE_URL."embeded/js/jquery.corner.js",	
	BASE_URL."embeded/js/jquery.linkedselect.js"	,
	BASE_URL."embeded/js/cookies.js"
	));
?>

<?php echo $this->javascriptfile( array(BASE_URL."embeded/packs/extjs//locale/ext-lang-{$this->_session->locale}.js")); ?>
<?php echo $this->javascriptfile(BASE_URL."tools/script/get/file/".rawurlencode(rawurlencode(BASE_URL."embeded/packs/ontoapp/localisation.js")),false) ?>
<?php echo $this->javascriptfile(BASE_URL."tools/script/get/file/".rawurlencode(rawurlencode(BASE_URL."embeded/js/gcv.js")),false) ?>
<?php echo $this->javascriptfile(array(BASE_URL."embeded/js/jquery.meio.mask.js",BASE_URL."embeded/js/jquery.metadata.js",BASE_URL."embeded/js/jquery.linkedselect.js")) ?>
<script type="text/javascript">
Ext.Loader.setConfig({enabled:true,scopeResetCSS:true ,  paths: {
    'Ext': '<?php echo BASE_URL?>embeded/packs/extjs/',
    'Ext.ux' : '<?php echo BASE_URL?>embeded/packs/extjs//examples/ux/'
}});
Ext.scopeResetCSS = true;
var site = { BASE_URL : "<?php echo BASE_URL ?>" };	
Ext.Loader.setConfig({ enabled: true });
</script>
<?php echo $this->headScript() ?>
<?php 
	echo $this->cssfile(array(BASE_URL."themes/liquid/css/general.css",
		BASE_URL."themes/liquid/css/dashboard.css",
		BASE_URL."themes/liquid/css/tables.css",
		BASE_URL."themes/liquid/css/pagination.css",
		BASE_URL."themes/liquid/css/forms.css"));
	echo $this->cssfile(array(
		BASE_URL."themes/system/css/ui/start1.8/ui.css",		
		BASE_URL."themes/system/css/tablesorter_blue.css",
		BASE_URL."themes/system/css/tree/apple/style.css",
		BASE_URL."embeded/packs/extjsthemes/gray-scope/css/ext-all-gray.css",
		BASE_URL."themes/liquid/css/ext-all-scoped-override.css"
	
		));

?>
</head>
<body>
<noscript>
	<p>You have to activate javascript.</p>
</noscript>
<?php echo $this->layout()->content?>
<script>
		jQuery(document).ready(function(){
			$("#ui-datepicker-div").css("display","none");
		});
</script>
<?php echo $this->placeholder("topendjs") ?>
</body>
</html>
