<?php if($this->style == "info"):?>
<div class="section">
<div class="quick_info">
<div class="quick_info_top">
<h2><?php echo $this->block('title'); ?></h2>
</div>
<div class="quick_info_content">
	<div style="padding: 10px;">   	
			<?php echo $this->block('content'); ?>		
	</div>
</div>
<span class="quick_info_bottom"></span></div>
</div>

<?php else :?>
<div class="section">
<!--[if !IE]>start title wrapper<![endif]-->
<div class="title_wrapper">
	<h2>	<?php echo $this->block('title'); ?></h2>
	<span class="title_wrapper_left"></span>							
<span class="title_wrapper_right" style="display: block;"></span></div>
<!--[if !IE]>end title wrapper<![endif]-->
<!--[if !IE]>start section content<![endif]-->
<div class="section_content">
	<!--[if !IE]>start section content top<![endif]-->
	<div class="sct_dark">
		<div class="sct_left">
			<div class="sct_right">
				<div class="sct_left">
					<div class="sct_right"> 	
						<div style="padding: 10px;">   																							
							<?php echo $this->block('content'); ?>	
						</div>												 
					</div>
				</div>
			</div>
		</div>
	</div>
	<!--[if !IE]>end section content top<![endif]-->
	<!--[if !IE]>start section content bottom<![endif]-->
	<span class="scb2"><span class="scb_left"></span><span class="scb_right"></span></span>
	<!--[if !IE]>end section content bottom<![endif]-->							
</div>
<!--[if !IE]>end section content<![endif]-->
</div>
<?php endif;?>