<?php echo $this->javascriptfile(BASE_URL . "embeded/js/Silverlight.js")?>
<?php echo $this->cssfile(BASE_URL."embeded/packs/extjs/examples/ux/css/CheckHeader.css") ?>
<?php echo $this->javascriptfile(BASE_URL."embeded/js/jquery.facebox.js") ?>
<?php echo $this->cssfile( BASE_URL."themes/system/css/facebox.css") ?>
<script type="text/javascript">
	var site = { BASE_URL : "<?php echo BASE_URL ?>" };
	
	Ext.Loader.setConfig({ enabled: true });
</script>
<div id="surface"></div>
<?php echo $this->javascriptfile(BASE_URL."embeded/packs/ontoapp/surface.js") ?>



