
<?php $this->placeholder("title")->set($this->_("List of organizations") )?>
<script
	src="<?php echo BASE_URL?>embeded/js/jquery.tablesorter.min.js"
	type="text/javascript"></script>
<script
	src="<?php echo BASE_URL?>embeded/js/jquery.tablesorter.pager.js"
	type="text/javascript"></script>




<?php echo $this->sexybutton ("href", $this->_("create") , array("add_new",""),  BASE_URL."sadmin/organizations/create"  ,array()) ?>


<table id="data" class="tablesorter display table">

	<thead>
		<tr>
			<th>#<?php echo $this->_ ( "ID" );?></th>
			<th><?php echo $this->_ ( "Name" );?></th>
			<th><?php echo $this->_ ( "Country" );?></th>
			<th></th>
		</tr>
	</thead>
	<tbody>

	<?php for($i = 0; $i < sizeof ( $this->list ); $i ++) :?>

		<tr class="<?php if($i % 2) echo "odd"; else echo "even"; ?>">
			<td><?php echo $this->list[$i]["idorganization"]?></td>
			<td><?php echo $this->list[$i]["name"]?></td>
			<td><?php echo $this->list[$i]["traduction_country"]?></td>
			<td>
			<div class="actions_menu">
			<ul>
				<li><a class="edit"
					href="<?php echo BASE_URL ?>sadmin/organizations/edit/id/<?php echo $this->list[$i]["idorganization"]?>"
					title="<?php echo $this->_("edit")?>"><?php echo $this->_("edit")?></a>
				</li>
			</ul>
			</div>
			</td>
		</tr>

		<?php endfor;?>
	</tbody>
</table>



<script type="text/javascript">
//<![CDATA[   
jQuery(document).ready(function() 
    { 
        $("#data").tablesorter(); 
    } 
); 
//]]>
</script>
