<?xml version="1.0" encoding="utf-8"?>
<videolist>

<responses><?php echo sizeof($this->results) ?></responses>

<programs>
<?php foreach($this->results as $program) : $program->init(); ?>
<program>

<infos>
<?php foreach($program->_data as $key =>$value ):?>
<?php if(!is_array($value)):?>
<<?php echo $key ?>><?php echo htmlspecialchars( $value,ENT_QUOTES,'UTF-8')  ?></<?php echo $key ?>>
<?php endif;?>
<?php endforeach;?>
<?php foreach($program->_data["details"] as $field ):?>
<field>
<?php $unFilteredKey = array("title","type","default_value","value","original_value","code");foreach($field as $key => $value ):if(in_array($key,$unFilteredKey)):?>
<<?php echo $key?>><?php echo htmlspecialchars( $value,ENT_QUOTES,'UTF-8')  ?></<?php echo $key?>>
<?php endif; endforeach; ?>
</field>
<?php endforeach;?>
</infos>

<chapters>
<?php $chapters = $program->getChapters();foreach($chapters as $chapter): ?>
<chapter>
<?php foreach($chapter->_data["details"] as  $field ): ?>
<field>
<?php foreach($field as $key => $value ): if(in_array($key,$unFilteredKey)): ?>
<<?php echo $key?>><?php echo htmlspecialchars( $value,ENT_QUOTES,'UTF-8')  ?></<?php echo $key?>>
<?php endif; endforeach; ?>
</field>
<?php  endforeach; ?>
</chapter>
<?php endforeach;?>
</chapters>

<pictures>
<?php $pictures = $program->getPictures();?><?php foreach($pictures as $picture):?>
<picture>
<?php foreach($picture->_data as $key =>$value ):?>
<<?php echo $key ?>><?php echo htmlspecialchars( $value,ENT_QUOTES,'UTF-8')  ?></<?php echo $key ?>>
<?php endforeach;?>
</picture>
<?php endforeach;?>
</pictures>

<videos>
<?php $videos = $program->getVideos();?><?php foreach($videos as $video):?>
<video>
<?php foreach($video->_data as $key =>$value ):?>
<<?php echo $key ?>><?php echo htmlspecialchars( $value,ENT_QUOTES,'UTF-8')  ?></<?php echo $key ?>>
<?php endforeach;?><?php $langues = $video->getLangues(); ?>
<languages>
<?php for($w=0 ; $w <sizeof($langues) ;$w++) : ?>
<language>
<lcid><?php echo (htmlspecialchars($langues[$w]["lcid"],ENT_QUOTES,'UTF-8')) ?></lcid>
<title><?php echo (htmlspecialchars($langues[$w]["libelle"],ENT_QUOTES,'UTF-8')) ?></title>
<picture><?php echo (htmlspecialchars($langues[$w]["picture"],ENT_QUOTES,'UTF-8')) ?></picture>
</language>
<?php endfor;?>
</languages>
</video>
<?php endforeach;?>
</videos>


</program>
<?php endforeach; ?>
</programs>
</videolist>
