<?php $this->placeholder("title")->set( $this->_("Consumption statistics by publications")  )?>
<?php echo $this->javascriptfile(BASE_URL."embeded/js/FusionCharts.js") ?>
<?php echo $this->javascriptfile(BASE_URL."embeded/packs/datepicker/js/datepicker.js") ?>
<?php echo $this->cssfile( BASE_URL."embeded/packs/datepicker/css/datepicker.css") ?>

<h3><?php echo $this->_("Consumption period")?> :</h3>

<?php echo $this->partial("stats_calendar_header.phtml",array("formAction"=>$this->url(array("controller"=>"stats","module"=>"prod","action"=>"publications"),null,true)))?>


<p class="large"></p>
<div id="chartdiv"></div>


<script type="text/javascript">

jQuery(document).ready(function(){	
        var myChart = new FusionCharts(BASE_URL + "embeded/flash/Charts/Column3D.swf", "myChartId", "98%", "500");
        myChart.setDataURL("<?php echo $this->dataUrl ?>");
        myChart.setTransparent(true);
        myChart.render("chartdiv");
           
});        
</script>

