<html>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<head>
<link rel="stylesheet" type="text/css"
	href="<?php echo THEME_PATH ?>/default.css" />
<script type="text/javascript"
	src="<?php echo THEME_PATH ?>/javascript/jquery-1.3.2.min.js"></script>
<script type="text/javascript"
	src="<?php echo THEME_PATH ?>/javascript/jquery.debug.js"></script>
<script type="text/javascript"
	src="<?php echo THEME_PATH ?>/javascript/jquery.media.js"></script>
<script type="text/javascript"
	src="<?php echo THEME_PATH ?>/javascript/overlib/overlib.js"></script>
<script type="text/javascript"
	src="<?php echo THEME_PATH ?>/javascript/functions_WMactiveX_pl.js"></script>
</head>
<body>

<?php echo $this->layout()->content ?>

<script language="javascript" type="text/javascript">
function goSheet(sheet){
    try{
        window.opener.changeSheet(sheet);
    }
    catch(error)
    {
	    var gcv_popup_width = 330;
	    var gcv_popup_height = 520;
	    var top=(screen.height-gcv_popup_height)/2;
	 	var left=(screen.width-gcv_popup_width)/2;
        pop_videolist =  window.open (sheet, "","WIDTH=" + gcv_popup_width +",HEIGHT=" + gcv_popup_height + ",left=" +left+ ",top="+top+",dependent");
    }
}
</script>

</body>
</html>


