<div class="accueil">
	<h1><?php echo $this->_("Welcome to")?> <?php echo $this->_config["productname"]?></h1>
	
	<p>
		<?php echo sprintf($this->_("Language interfaces is deducted from your browser.<br/>The current language is <strong>%s</strong>.<br />If you want to change language, click on the flag in the bottom of this page.","none"),
		$this->_session->locale)?>
	</p>
</div>
<!-- 
<img src="<?php echo BASE_URL ?>themes/system/pics/clap.jpg" />
 -->