<?php echo $this->javascriptfile(BASE_URL."tools/script/get/file/".rawurlencode(rawurlencode(BASE_URL."embeded/js/jquery.validationEngine.langue.js")),false) ?>
<?php echo $this->javascriptfile(BASE_URL."embeded/js/jquery.validationEngine.js") ?>
<?php echo $this->cssfile( BASE_URL."themes/system/css/validationEngine.jquery.css") ?>


<?php $this->placeholder("title")->set($this->_("Create a new field"))?>
<form action="<?php echo BASE_URL?>sadmin/fields/registernewfield"
	method="post" id="fieldform">
<fieldset><legend></legend>


<p><label><?php	echo $this->_ ( "Name" )?></label> <span><input type="text" maxlength="" name="title" id="title" class="validate[required]" title="<?php echo $this->_("Name of the field." )?>"/></span></p>
<p><label><?php	echo $this->_ ( "Code" )?></label> <span><?php echo $this->formText("code", "" ,array("class"=>"validate[required,ajax[ajaxCode],custom[noSpecialCaracters]]","title"=> $this->_("Code of the field. No space and special characters allowed !" ) )) ?>
</span></p>
<p><label><?php echo $this->_ ( "Type" )?></label> <span> <select title="<?php echo $this->_("Type of the field. Cannot be changed once chosen." )?>" id="type" name="type">
	<option value="TEXT"><?php	echo $this->_ ( "text" )?></option>
	<option value="ENUM"><?php	echo $this->_ ( "enum" )?></option>
	<option value="ENUMMULTI"><?php	echo $this->_ ( "enum multi" )?></option>
	<option value="DATE"><?php echo $this->_ ( "date" )?></option>
	<option value="BOOLEAN"><?php echo $this->_ ( "boolean" )?></option>
	<option value="COMPLEXBOOLEAN"><?php	echo $this->_ ( "complex boolean" )?></option>
	<option value="TEXTAREA"><?php	echo $this->_ ( "textarea" )?></option>
	<option value="FILE"><?php	echo $this->_ ( "file" )?></option>
	<option value="PICTURE"><?php	echo $this->_ ( "picture" )?></option>
</select> </span></p>
<p><label><?php	echo $this->_ ( "Mask" )?></label> <span><input	 title="<?php echo $this->_("Input mask. For more documentation, you have to see jquery.meio.mask.js documentation." )?>" type="text" maxlength="" name="mask" id="mask" /></span></p>
<p><label><?php echo $this->_ ( "Default value" )?></label> <span><textarea title="<?php echo $this->_("This is the default value of the field.") ?>"	name="default_value" id="default_value" rows="5" cols="10"></textarea></span>
</p>

<p><label><?php	echo $this->_ ( "Category" )?></label> <span>
<select	id="category" name="category" title="<?php echo $this->_("Grouping fields by personal affinities" )?>">
	<option value=""></option>
	<?php for($i=0;$i<sizeof($this->cat);$i++):?>
	<option value="<?php echo $this->cat[$i]["id"] ?>"><?php echo $this->cat[$i]["value"] ?></option>
	<?php endfor;?>
</select> </span></p>

<p><label><?php	echo $this->_ ( "Table" )?></label> <span><input	 title="<?php echo $this->_("Table name in BDD. Name is deducted from the code.")?>" type="text" maxlength="" name="table_ref" id="table_ref"	disabled="disabled" /></span></p>
<p><label><?php	echo $this->_ ( "Parent" )?></label><span><input	 title="<?php echo $this->_("Parent is the code of another field.")?>" type="text" maxlength="" name="parent" disabled="disabled" id="parent" /></span></p>

<p><label><?php echo $this->_ ( "Help" )?></label> <span><textarea	title="<?php echo $this->_("This is the tooltip of the field in the generated form.")?>" name="help" id="help" rows="5" cols="10"></textarea></span>
</p>

<p><label>&nbsp;</label><span> <?php echo $this->sexybutton ("submit", $this->_("save"), array("send_form_btn"), null) ?> </span></p>


</fieldset>
</form>




<script type="text/javascript">
//<![CDATA[   
var field_not_ok = [<?php echo $this->field_not_ok ?>];

jQuery(document).ready(function(){
    $("form").submit(function(){
    	var state = true;	
    	
    	if(!state)alert("<?php echo $this->_( "Please check your entry, some fields are wrong." )?>");
    	//return true;
    	return state;
    	
    })
    $("#fieldform").validationEngine();    
    jQuery.each(field_not_ok, function() {
      $("#" + this).addClass("input_nok");
    });    
    
    <?php foreach ( $_POST as $key => $value ) {	?>
    $("#<?php echo $key?>").val('<?php echo $value?>');
    <?php }	?>
        
    $("#type").change(function(){
            setField($(this).val());
    });
    
    <?php if (isset ( $_POST ['fieldtype'] )) :	?>
        setField("<?php echo $_POST ['fieldtype']?>");    
        <?php else : ?>
        setField("1");
   <?php endif;	?>
    
    
});
function setField(value){
            switch(value){
            case "TEXT" : 
            $('#table_ref').attr("disabled","disabled");
            $('#parent').attr("disabled","disabled");
          
            break;
            case "ENUM" :  case "ENUMMULTI" :  
            $('#table_ref').removeAttr("disabled");
            $('#parent').removeAttr("disabled");
          
            break;
            case "DATE" : 
            $('#table_ref').attr("disabled","disabled");
            $('#parent').attr("disabled","disabled");
            
            break;
            case "BOOLEAN" : 
            $('#table_ref').attr("disabled","disabled");
            $('#parent').attr("disabled","disabled");
         
            case "COMPLEXBOOLEAN" : 
             $('#table_ref').attr("disabled","disabled");
            $('#parent').attr("disabled","disabled");
          
            break;
            case "TEXTAREA" : 
            $('#table_ref').attr("disabled","disabled");
            $('#parent').attr("disabled","disabled");
           
        }
    
}

function checktitleoffield(value) {
        $.ajax({
            type:"POST",
            url:"<?php echo BASE_URL?>admin/profil/checktitleoffield/format/ajax",
            data:"&title=" + value,
            success: function(msg){
               
                if(msg == 1){
                    $('#error').html("<?php echo $this->_( "This name already exists." )?>");
                    $('#error').css("display","block");
                }
                
                else{
                    $('#error').css("display","none");    
                    $('#error').html("");
                }
          }
    })
}  

function checktitleoffield2(value) {
        $.ajax({
            type:"POST",
            url:"<?php echo BASE_URL?>admin/profil/checktitleoffield2/format/json",
            data:"&title=" + value,
            success: function(data){}
    })
}  

//]]>
</script>

<div class="error"
	id="error" style="display: none"></div>
<br />

<?php echo $this->systemMessage( $this->_ ( "Check the searchable case to allow people to search with this criteria." ),1)?>
<?php echo $this->systemMessage( $this->_ ( "By choosing 1,2,3,4,5, you have the possibility to aggregate fields according to your own criterias." ),1)?>






