<form action="<?php
echo BASE_URL?>admin/profil/confirmdeletegroup"
	method="post">

<p><?php
echo $this->_ ( "You are going to delete the group : " ) . $this->group [0] ['udg_title'];
?> <br />
<?php
echo $this->_ ( "Do you want to confirm ?" );
?> <br />
</p>
<p><input type="hidden" name="udg_id" 	value="<?php echo $this->group [0] ['udg_id']?>" /> 
	<?php echo $this->sexybutton ("submit", $this->_("confirm"), array("send_form_btn"), null,array("id"=>"submit")) ?>
	<?php echo $this->sexybutton ("button", $this->_("back"), array("send_form_btn"), null,array("id"=>"")) ?>







</p>

</form>
<script type="text/javascript">
//<![CDATA[   
jQuery(document).ready(function() 
    { 
        $("#back").click(function(){history.back();}); 
    } 
); 
//]]>
</script>
