<?php $this->placeholder("title")->set($this->_("List of fields"))?>
<script
	src="<?php echo BASE_URL?>embeded/js/jquery.tablesorter.min.js"
	type="text/javascript"></script>
<script
	src="<?php echo BASE_URL?>embeded/js/jquery.tablesorter.pager.js"
	type="text/javascript"></script>





<?php echo $this->sexybutton ("href", $this->_("create") , array("add_new",""),  BASE_URL."sadmin/fields/createfield"  ,array()) ?>


<table id="data" class="tablesorter display table">

	<thead>
		<tr>
			<th>#<?php echo $this->_ ( "ID" );?></th>
			<th><?php echo $this->_ ( "Name" );?></th>
			<th><?php echo $this->_ ( "Code" );?></th>
			<th><?php echo $this->_ ( "Type" );?></th>
			<th><?php echo $this->_ ( "Actions" );?></th>
		</tr>
	</thead>
	<tbody>

	<?php for($i = 0; $i < sizeof ( $this->fields ); $i ++) :?>

		<tr class="<?php if($i % 2) echo "odd"; else echo "even"; ?>">
			<td><?php echo $this->fields [$i] ["idfield"]; ?></td>
			<td><?php echo $this->fields [$i] ["title"];?></td>
			<td><?php echo $this->fields [$i] ["code"];?></td>
			<td><?php echo $this->fields [$i] ["type"]; ?></td>
			<td>

			<div class="actions_menu">

			<ul>
		
					<?php if ($this->fields [$i] ["is_editable"]) :	?>
				<li><a	href="<?php	echo BASE_URL?>sadmin/fields/editfield/field/<?php echo $this->fields [$i] ["idfield"];?>"	class="edit" title="<?php echo $this->_ ( "edit" )?>"><?php echo $this->_ ( "edit" )?></a></li>
					<?php endif;?>
					<li><a href="<?php echo BASE_URL ?>sadmin/translations/list/id/<?php echo $this->fields [$i] ["idfield"];?>" title="" class="edit"><?php echo $this->_("translations") ?></a></li>							
					<?php if ($this->fields [$i] ["is_editable"] > 1) :	?>
				<li><a	href="<?php echo BASE_URL?>sadmin/fields/confirmdeletefield/field/<?php echo $this->fields [$i] ["idfield"];  ?>" title="<?php echo $this->_ ( "delete" )?>" class="delete"><?php echo $this->_ ( "delete" ) ?></a></li>
					<?php endif;?>
			</ul>

			</div>

			</td>
		</tr>

		<?php endfor;?>
	</tbody>
</table>
		<?php // echo $this->pager ( $this->numrows );?>


<div id="dialog" title="<?php echo  $this->_("Removal confirmation") ?>">
<p><span class="ui-icon ui-icon-alert"
	style="float: left; margin: 0 7px 20px 0;"></span><?php echo  $this->_("Are you sure to delete this field ?") ?></p>
</div>


<script type="text/javascript">
//<![CDATA[   
jQuery(document).ready(function() 
    { 
        $("#data").tablesorter(); 
 var _destroyUrl;
    	
        $('a.delete').click(function() {
    		$('#dialog').dialog('open');
    		_destroyUrl = $(this).attr("href");
    		return false;
    	})
    	;
    	
    	$("#dialog").dialog({
    		
    		bgiframe: true,
    		resizable: false,
    		height:140,
    		modal: true,
    		autoOpen:false,
    		overlay: {
    			backgroundColor: '#000',
    			opacity: 0.5
    		},
    		buttons: {
    			'<?php echo $this->_("Delete")?>': function() {
    				$(this).dialog('close');
    				document.location.href = (_destroyUrl);
    			},
    			<?php echo $this->_("Cancel")?>: function() {
    				$(this).dialog('close');
    			}
    		}
    	});
    } 
); 
//]]>
</script>
