<h3><?php
echo $this->_ ( "Actions" )?></h3>


<table width="100%" border="0" cellpadding="0" cellspacing="0">

	<tr align="left">
		<td><a href="<?php
		echo BASE_URL?>admin/profil/createextension"
			class="mainlevel"><?php
			echo $this->_ ( "Create extension" )?></a></td>
	</tr>
	<tr align="left">
		<td><a href="<?php
		echo BASE_URL?>admin/profil/creategroup"
			class="mainlevel"><?php
			echo $this->_ ( "Create group" )?></a></td>
	</tr>
	<tr align="left">
		<td><a href="<?php
		echo BASE_URL?>admin/profil/modifyextension"
			class="mainlevel"><?php
			echo $this->_ ( "Modify extension" )?></a></td>
	</tr>
	<tr align="left">
		<td><a href="<?php
		echo BASE_URL?>admin/profil/modifygroup"
			class="mainlevel"><?php
			echo $this->_ ( "Modify group" )?></a></td>
	</tr>
	<tr align="left">
		<td><a href="<?php
		echo BASE_URL?>admin/profil/modifytable"
			class="mainlevel"><?php
			echo $this->_ ( "Modify table" ) ?></a></td>
	</tr>


	</td>
	</tr>
</table>
