
<?php $this->placeholder("title")->set($this->_("List of tables"))?>
<script
	src="<?php echo BASE_URL?>embeded/js/jquery.tablesorter.min.js"
	type="text/javascript"></script>
<script
	src="<?php echo BASE_URL?>embeded/js/jquery.tablesorter.pager.js"
	, type="text/javascript"></script>


<table id="data" class="tablesorter display table">

	<thead>
		<tr>

			<th><?php echo $this->_ ( "Name" );	?></th>
			<th><?php echo $this->_ ( "Of field" );	?></th>

			<th><?php	echo $this->_ ( "Actions" );?></th>


		</tr>
	</thead>
	<tbody>

	<?php
	for($i = 0; $i < sizeof ( $this->tables ); $i ++) :
	?>

		<tr class="<?php if($i % 2) echo "odd"; else echo "even"; ?>">
			<td><?php echo $this->tables [$i] ["table_ref"];?></td>
			<td><?php echo $this->tables [$i] ["title"]; ?></td>
			<td>
			<div class="actions_menu">
			<ul>
				<li><a class="edit"
					href="<?php	echo BASE_URL?>sadmin/fields/edittable/table/<?php echo $this->tables [$i] ["table_ref"]; ?>"
					title="<?php echo $this->_ ( "edit" )?>"><?php	echo $this->_ ( "edit" )?></a></li>

			</ul>
			</div>

			</td>
		</tr>

		<?php
		endfor;
		?>


	</tbody>

</table>

		<?php
		// echo $this->pager ( $this->numrows );
		?>

<script type="text/javascript">
//<![CDATA[   
jQuery(document).ready(function() 
    { 
        $("#data").tablesorter(); 
    } 
); 
//]]>
</script>
