<playlists>
<?php for($i=0 ; $i <sizeof($this->playlists) ;$i++) : ?>
<playlist>
<title><![CDATA[<?php echo utf8_encode(htmlspecialchars($this->playlists[$i]['title'])) ?>]]></title>
<description>
<![CDATA[<?php echo utf8_encode(htmlspecialchars($this->playlists[$i]['description'])) ?>]]>
</description>
<picture>
<?php echo utf8_encode(htmlspecialchars($this->playlists[$i]['picture'])) ?>
</picture>
<group>
<?php echo utf8_encode(htmlspecialchars($this->playlists[$i]['group'])) ?>
</group>
<ressource>
http://
<?php echo $_SERVER['HTTP_HOST']?><?php echo BASE_URL ?>
rest/playlist/
<?php echo $this->publicationkey ?>
/id/
<?php echo htmlspecialchars($this->playlists[$i]['id']) ?>
</ressource>
</playlist>
<?php endfor;?>
</playlists>
