
<?php echo $this->javascriptfile(BASE_URL."tools/script/get/file/".rawurlencode(rawurlencode(BASE_URL."embeded/js/jquery.validationEngine.langue.js")),false) ?>
<?php echo $this->javascriptfile(BASE_URL."embeded/js/jquery.validationEngine.js") ?>
<?php echo $this->cssfile( BASE_URL."themes/system/css/validationEngine.jquery.css") ?>

<?php $this->placeholder("title")->set($this->_("Edit password"))?>

<a class="button check_all"
	href="<?php echo BASE_URL?>sadmin/users/edit/id/<?php echo $this->iduser ?>"><span><span><?php echo $this->_("Back to user")?></span></span></a>

<form action="<?php echo BASE_URL ?>sadmin/users/updatepassword" id="userpassform"
	method="post">
<fieldset>

<p><label><?php echo $this->_("Type password")?> :</label> <span><?php print $this->formPassword("pass1",null,array("class"=>"validate[required]"));?></span>
</p>
<p><label><?php echo $this->_("Type password again")?> :</label> <span><?php print $this->formPassword("pass2",null,array("class"=>"validate[required],confirm[pass1]"));?></span>
</p>
<p><label>&nbsp;<?php print $this->formHidden("iduser",$this->iduser,null)?></label>
<span>
<?php echo $this->sexybutton ("submit", $this->_("update password"), array("send_form_btn"), null,array("id"=>"")) ?>
</span></p>
</fieldset>
</form>


<script type="text/javascript">
//<![CDATA[   

jQuery(document).ready(function(){
	   $("#userpassform").validationEngine();  
});

//]]>
</script>