<?php $this->placeholder("title")->set($this->_("Edit menu"))?>

<?php echo $this->javascriptfile( BASE_URL."embeded/js/jquery.tree.js") ?>
<?php echo $this->javascriptfile( BASE_URL."embeded/js/jquery.json-2.2.min.js") ?>


<div class="droparea folder">
<h2><?php echo $this->_("Menu elements in stock") ?></h2>
<div id="zone1">
<ul id="list1">
<?php  foreach( $this->menusArrayDispo as   $keyValue ) :	?>
	<li id="field_<?php echo$keyValue ["idmenu"]?>"><a href="#"><ins> </ins>
	<?php echo $keyValue ["title"]?></a></li>
	<?php endforeach;; 	?>
</ul>
</div>
</div>


<div class="droparea folder">
<h2><?php echo $this->_("Allocated menu elements ") ?></h2>
<div id="zone2">
<ul id="list2">
</ul>
</div>
</div>


<br style="clear: both" />
<form id="formMenu" action="<?php echo BASE_URL ?>sadmin/users/savemenu"	method="post"><input type="hidden" name="listAffected"	id="listAffected" value=""> <input type="hidden" name="idproduction"	id="idproduction"	value="<?php echo isset($this->idproduction)?$this->idproduction:0  ?>">

	

	<?php echo $this->sexybutton ("submit", $this->_("update"), array("send_form_btn"), null,array("id"=>"")) ?>	
	<a class="button red_btn" href="<?php echo BASE_URL?>sadmin/users/delmenu/iduser/<?php echo $this->iduser ?>/type/<?php echo $this->typeModule ?>/ressource/<?php echo $this->idressource?>"><span><span><?php echo $this->_("delete user personalization")?></span></span></a> 	
	
	<?php echo $this->formHidden("iduser",$this->iduser)?>
	<?php echo $this->formHidden("typeModule",$this->typeModule)?>
	<?php echo $this->formHidden("idressource",$this->idressource)?>
</form>



	<?php if($this->idproduction > 0):?>

	<?php else : ?>
		<?php echo $this->systemMessage($this->_("You can specify a different list and order for each production account. Go to the production list and click menu for the production account you want to edit."),1)?>
	<?php endif;?>


<script type="text/javascript">
//<![CDATA[
jQuery(document).ready(function(){   
	$("#formMenu").submit(function(){				
		var str = $.toJSON(jQuery.tree.reference("#zone2" ).get(0,"json"));$("#listAffected").val(str);		
	});
	
       $("#zone2").tree({
    	   "ui":{ "theme_path" : "<?php echo BASE_URL?>themes/system/css/tree/default/style.css"},
    	   "rules":{"multitree":"all"},
    	   "callback" : {
        	   	"onmove":function(NODE, REF_NODE, TYPE, TREE_OBJ, RB){ var str = $.toJSON(TREE_OBJ.get(0,"json"));$("#listAffected").val(str); },
        	   	"onload":function(TREE_OBJ) { var str = $.toJSON(TREE_OBJ.get(0,"json"));$("#listAffected").val(str); }
   	   	},
    	   "data":{
    		   		type : "json",
    		   		opts : {static :<?php echo $this->menusJsonOrderedAffected ?>} 
        	   }
           });

       $("#zone1").tree({
    	   "ui":{ "theme_path" : "<?php echo BASE_URL?>themes/system/css/tree/default/style.css"},
    	   "rules":{"multitree":"all"}
        });
});
//]]>
</script>


