
<?php if (sizeof ( $this->messages ) > 0 ) :	?>
<div class="error">
<div class="error_inner"><strong><?php echo $this->_("Access Denied")?></strong>
| <span><?php  echo $this->messages [$i] 	?></span></div>
</div>
<?php endif; ?>

<!--[if !IE]>start login<![endif]-->
<form method="post"
	action="<?php echo $this->url(array("action"=>"forgottenpasswordstep2","controller"=>"user","module"=>$this->getParam("module")),null,true) ?>"
	id="Form">
<fieldset>
<h1 id="logo"><a href="<?php echo BASE_URL ?>"><?php echo $this->_("websitename Administration Panel")?></a></h1>
<div class="formular">
<div class="formular_inner"><label> <strong><?php echo $this->_("Your email")?>
:</strong> <span class="input_wrapper"><?php echo $this->formText("youremail",null,array("class"=>"validate[email,required]"))?>
</span> </label> <?php echo $this->formHidden("url",$this->url)?>

<ul class="form_menu">
	<li><span class="button"><span><span><?php echo $this->_("Next")?></span></span><input
		type="submit" /></span></li>
</ul>
</div>
</div>
</fieldset>
</form>

<!--[if !IE]>end login<![endif]-->


<script type="text/javascript">
jQuery(document).ready(function(){
	$("#Form").validationEngine();
});
</script>
