




<?php if (sizeof ( $this->messages ) > 0 ) :	?>
<div class="error">
<div class="error_inner"><strong><?php echo $this->_("Access Denied")?></strong>
| <span><?php  echo $this->messages [$i] 	?></span></div>
</div>
<?php endif; ?>


<!--[if !IE]>start login<![endif]-->
<form method="post"
	action="<?php echo $this->url(array("action"=>"forgottenpasswordstep3","controller"=>"user","module"=>$this->getParam("module")),null,true) ?>">
<fieldset>
<h1 id="logo"><a href="<?php echo BASE_URL ?>"><?php echo $this->_("websitename Administration Panel")?></a></h1>
<div class="formular">
<div class="formular_inner"><label> <strong><?php echo $this->_("A request has been send.") ?></strong><br />
<br />
</label>


<ul class="form_menu">

	<li><a
		href="<?php echo $this->url(array("action"=>"disconnect","controller"=>"user","request"=>Zend_Controller_Front::getInstance()->getRequest()->getParam("action"))) ?>"><span><span><?php echo $this->_("Disconnect")?></span></span></a></li>
</ul>

</div>
</div>
</fieldset>
</form>

<!--[if !IE]>end login<![endif]-->

