<?php $this->placeholder("title")->set($this->_( "Create new menu"))?>
<form method="post" action="<?php echo BASE_URL ?>sadmin/menu/save">

<fieldset>


<p><label><?php echo $this->_("Title") ?></label> <span><?php echo $this->formText("title", "" ,null) ?></span>
</p>
<p><label><?php echo $this->_("Url") ?></label> <span><?php echo $this->formText("url", "" ,null) ?></span>
</p>
<p><label>&nbsp;</label><span> OR </span></p>

<p><label><?php echo $this->_("Component") ?></label> <span><?php echo $this->formSelect('idcomponent', 2, null, $this->listComponents); ?></span>
</p>
<p><label>&nbsp;</label> <span><?php echo $this->sexybutton ("submit", $this->_("save"), array("send_form_btn"), null) ?></span></p>



</fieldset>
</form>



<?php echo $this->systemMessage( $this->_ ( "Be carefull, The url parameter takes advantage over any other." ),1)?>

<script type="text/javascript">
//<![CDATA[   
var field_not_ok = [<?php echo $this->field_not_ok ?>];
jQuery(document).ready(function(){       
    jQuery.each(field_not_ok, function() {
      $("#" + this).addClass("input_nok");
    });  
    <?php foreach ( $this->rawData as $key => $value ) {	?>
		$("#<?php echo $key?>").val('<?php echo $this->escape( $value ); ?>');
    <?php }	?>
});
//]]>
</script>
