
<?php $this->placeholder("title")->set($this->_(  "List of menu" ))?>
<script
	src="<?php echo BASE_URL?>embeded/js/jquery.tablesorter.min.js"
	type="text/javascript"></script>
<script
	src="<?php echo BASE_URL?>embeded/js/jquery.tablesorter.pager.js"
	type="text/javascript"></script>
<script
	src="<?php echo BASE_URL?>embeded/js/jquery.facebox.js"
	type="text/javascript"></script>

<link
	rel="stylesheet" type="text/css"
	href="<?php echo BASE_URL ?>themes/system/css/facebox.css" media="all" />


<?php echo $this->sexybutton ("href", $this->_("create") , array("add_new",""),  BASE_URL."sadmin/menu/create"  ,array()) ?>

<table id="data" class="tablesorter display table">

	<thead>
		<tr>
			<th>#<?php echo $this->_ ( "ID" );?></th>
			<th><?php echo $this->_ ( "Title" );?></th>
			<th><?php echo $this->_ ( "Component" );?></th>
			<th><?php echo $this->_ ( "Module" );?></th>

			<th></th>
		</tr>
	</thead>
	<tbody>

	<?php for($i = 0; $i < sizeof ( $this->list ); $i ++) :?>

		<tr class="<?php if($i % 2) echo "odd"; else echo "even"; ?>">
			<td><?php echo $this->list[$i]["idmenu"]?></td>
			<td><?php echo $this->list[$i]["deftitle"]?></td>
			<td><?php echo $this->list[$i]["functionname"]?></td>
			<td><?php echo $this->list[$i]["moduletype"]?></td>

			<td>


			<div class="actions_menu">
			<ul>
			
				<li><a
					href="<?php echo BASE_URL ?>sadmin/menu/edit/id/<?php echo $this->list[$i]["idmenu"]?>"
					title="<?php echo $this->_("edit") ?>" class="edit"><?php echo $this->_("edit") ?></a></li>
					<li><a href="<?php echo BASE_URL ?>sadmin/translations/listtranslationmenu/id/<?php echo $this->list[$i]["idmenu"]?>" title="" class="edit"><?php echo $this->_("translations") ?></a></li>
	<li><a 	href="<?php echo BASE_URL ."sadmin/menu/deletemenu/id/". $this->list[$i]["idmenu"]  ?>"	class="delete"><?php echo $this->_("delete") ?></a></li>

			</ul>
			</div>


			</td>
		</tr>

		<?php endfor;?>
	</tbody>
</table>


<div id="dialog" title="<?php echo  $this->_("Removal confirmation") ?>">
<p><span class="ui-icon ui-icon-alert"
	style="float: left; margin: 0 7px 20px 0;"></span><?php echo  $this->_("Are you sure to delete this menu entry ?") ?></p>
</div>

<script type="text/javascript">
//<![CDATA[   
jQuery(document).ready(function() 
    { 
        $("#data").tablesorter(); 
        var _destroyUrl;
    	
        $('a.delete').click(function() {
    		$('#dialog').dialog('open');
    		_destroyUrl = $(this).attr("href");
    		return false;
    	});
    	
    	$("#dialog").dialog({
    		
    		bgiframe: true,
    		resizable: false,
    		height:140,
    		modal: true,
    		autoOpen:false,
    		overlay: {
    			backgroundColor: '#000',
    			opacity: 0.5
    		},
    		buttons: {
    			'<?php echo $this->_("Delete")?>': function() {
    				$(this).dialog('close');
    				document.location.href = (_destroyUrl);
    			},
    			<?php echo $this->_("Cancel")?>: function() {
    				$(this).dialog('close');
    			}
    		}});
    } 
); 
//]]>
</script>
