<?php $this->placeholder("title")->set($this->_("List  of publications"))?>



<table id="data" class="tablesorter display table">
	<thead>
		<tr>
			<th><?php echo $this->_ ( "name" );?></th>
			<th><?php echo $this->_ ( "count of programs" );?></th>
			<th></th>
		</tr>
	</thead>
	<tbody>
	<?php foreach ($this->list as $item): ?>
		<tr class="<?php echo $this->cycle(array("odd","even"))->next()?>">
			<td><?php print ( $item["name"]) ?></td>
			<td><?php print ( $item["count"]) ?></td>
			<td>
			<div class="actions_menu">
			<ul>
				<li><a class="edit"
					href="<?php print BASE_URL ?>prod/pub/edit/idpublication/<?php print $item["idpublication"]?>"><?php echo $this->_("edit") ?></a></li>
			</ul>
			</div>
			</td>
		</tr>
		<?php endforeach; ?>
	</tbody>
</table>





<div id="dialog"
	title="<?php echo  $this->_("Removal confirmation") ?>">
<form method="post" action="<?php echo BASE_URL ?>prod/group/delete"
	id="formProgramToDelete">
<p><span class="ui-icon ui-icon-alert"
	style="float: left; margin: 0 7px 20px 0;"></span> <?php echo  $this->_("This group of programs will be deleted. Are you sure ?") ?>
<input type="hidden" id="keyToDelete" name="keyToDelete" value="" /></p>

</form>
</div>


<script type="text/javascript">

function deleteGroup(key){	
	$("#keyToDelete").val(key);
	$('#dialog').dialog('open');
}


jQuery(document).ready(function() 
{ 
            var _destroyUrl;    	
            $('a.delete').click(function() {
            	$('#dialog').dialog('open');
            	_destroyUrl = $(this).attr("href");
            	return false;
            });
            $("#dialog").dialog({            	
            	bgiframe: true,
            	resizable: false,            	
            	modal: true,
            	autoOpen:false,
            	overlay: {
            		backgroundColor: '#000',
            		opacity: 0.5
            	},
            	buttons: {
            		'<?php echo $this->_("Delete")?>': function() {
            			$(this).dialog('close');
            			$("#formProgramToDelete").trigger("submit");            			
            		},
            		<?php echo $this->_("Cancel")?>: function() {
            			$(this).dialog('close');
            		}
            	}
            });
});
</script>
